<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Addefforts.aspx.cs" Inherits="EffortManagement.Addefforts" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>:::: Time Sheet Management ::::</title>
    <link href="Content/efforts.css" rel="stylesheet"  media="all"/>
    <script  type="text/javascript" >
    
    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode != 46 && charCode > 31
          && (charCode < 48 || charCode > 57))
            return false;

        return true;
    }
   
    </script>
</head>
<body>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server"
            EnablePageMethods="true">
        </asp:ScriptManager>
        <div>
            <asp:LinkButton runat="server" ID="BtnBack" Text="<< Back" PostBackUrl="~/Calender.aspx" CausesValidation="false"></asp:LinkButton>
            <asp:Label runat="server" ID="LblPagemode" Visible="false"></asp:Label>
        </div>
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" 
                OnRowDataBound="GridView1_RowDataBound" DataKeyNames="id"  BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellPadding="3"   
CellSpacing="1" GridLines="None">
<Columns>

    <asp:TemplateField HeaderText="TicketNumber">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="TextBox2" runat="server" OnTextChanged="TxtTicketNumber_Changed" Text='<%# Bind("TicketNumber") %>'>  
                                </asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("TicketNumber") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

     <asp:TemplateField HeaderText="TicketType">  
                            <EditItemTemplate>  
                                <asp:DropDownList ID="DropDownList2" runat="server" OnSelectedIndexChanged="DrpTicketType_SelectedIndexChanged"  
SelectedValue='<%# Bind("TicketType") %>'>  
                                    <asp:ListItem>--Choose One--</asp:ListItem>  
                                    <asp:ListItem>Meeting</asp:ListItem>  
                                    <asp:ListItem>Incident Request</asp:ListItem>
                                    <asp:ListItem>End to End feedback</asp:ListItem>
                                </asp:DropDownList>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label4" runat="server" Text='<%# Bind("TicketType") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

     <asp:TemplateField HeaderText="Application">  
                            <EditItemTemplate>  
                                <asp:DropDownList ID="DropDownList3" runat="server" OnSelectedIndexChanged="DrpApplications_SelectedIndexChanged"  
SelectedValue='<%# Bind("Application") %>'>  
                                    <asp:ListItem>--Choose One--</asp:ListItem>  
                                    <asp:ListItem>Customer service gurantee</asp:ListItem>  
                                    <asp:ListItem>End to End feedback</asp:ListItem>
                                </asp:DropDownList>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label5" runat="server" Text='<%# Bind("Application") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

     <asp:TemplateField HeaderText="Application Type">  
                            <EditItemTemplate>  
                                <asp:DropDownList ID="DropDownList4" runat="server"   
SelectedValue='<%# Bind("ApplicationType") %>'>  
                                    <asp:ListItem>--Choose One--</asp:ListItem>  
                                    <asp:ListItem>Type1</asp:ListItem>  
                                    <asp:ListItem>Type2</asp:ListItem>
                                    <asp:ListItem>Type3</asp:ListItem>
                                </asp:DropDownList>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label6" runat="server" Text='<%# Bind("ApplicationType") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>
    
     <asp:TemplateField HeaderText="Classification">  
                            <EditItemTemplate>  
                                <asp:DropDownList ID="DropDownList5" runat="server"   
SelectedValue='<%# Bind("Classification") %>'>  
                                    <asp:ListItem>--Choose One--</asp:ListItem>  
                                    <asp:ListItem>ID Creation</asp:ListItem>  
                                    <asp:ListItem>ID Unlock</asp:ListItem>
                                    
                                </asp:DropDownList>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label7" runat="server" Text='<%# Bind("Classification") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

       <asp:TemplateField HeaderText="Description">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("Description") %>'>  
                                </asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label8" runat="server" Text='<%# Bind("Description") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>
    
    <asp:TemplateField HeaderText="Created On">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("CreatedOn") %>'>  
                                </asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label10" runat="server" Text='<%# Bind("CreatedOn") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>

     <asp:TemplateField HeaderText="Remarks">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("Remarks") %>'>  
                                </asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("Remarks") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>


     <asp:TemplateField HeaderText="Efforts(In Minutes)">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="TextBox6" runat="server" Text='<%# Bind("Efforts") %>'>  
                                </asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label3" runat="server" Text='<%# Bind("Efforts") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>



</Columns>

             </asp:GridView>
            <asp:Button runat="server" ID="BtnAdd" Text="Add More" OnClick="AddRow" CausesValidation="false" />

           <asp:Button runat="server" ID="BtnSave" Text="Save"  CausesValidation="true" />

            <asp:Button runat="server" ID="Btndelete" Text="X" ForeColor="Red" CssClass="repeateritemlabel" CausesValidation="false" CommandName="delete" OnClick="Btndelete_Click" /><%--Visible="false" />--%>

         </div>
    </form>
</body>
</html>
